---
- name: make a build dir
  file: state=directory name=/root/postgresql-dockerized

- name: put Dockerfile
  template: src=Dockerfile dest=/root/postgresql-dockerized/Dockerfile

- name: put postgresql.rb
  template: src=postgresql.rb dest=/root/postgresql-dockerized/postgresql.rb

- name: put prestart.sh
  template: src=prestart.sh dest=/root/postgresql-dockerized/prestart.sh mode=755

- name: put pgdg.list
  template: src=pgdg.list dest=/root/postgresql-dockerized/pgdg.list

- name: build a Docker image for postgresql
  command: docker build -t gitinsky/postgresql:0.2.1 --rm /root/postgresql-dockerized

- name: tag it as latest
  command: docker build -t gitinsky/postgresql:latest --rm /root/postgresql-dockerized
